sudo: required
services:
    - docker

# look in the client directory for the build context
# you could add more scripts and build contexts if you have other tests
before_install:
    - docker build -t callistachang/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=TRUE callistachang/react-test npm test

after_success:
    - docker build -t callistachang/multi-client ./client
    - docker build -t callistachang/multi-nginx ./nginx 
    - docker build -t callistachang/multi-server ./server 
    - docker build -t callistachang/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push callistachang/multi-client
    - docker push callistachang/multi-nginx 
    - docker push callistachang/multi-server 
    - docker push callistachang/multi-worker
# push them to dockerhub!