sudo: required
services:
    - docker

# look in the client directory for the build context
# you could add more scripts and build contexts if you have other tests
before_install:
    - docker build -t callistachang/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run callistachang/react-test npm test -- --coverage

after_success:
    - docker build -t callistachang/multi-client ./client
    - docker build -t callistachang/multi-nginx ./nginx 
    - docker build -t callistachang/multi-server ./server 
    - docker build -t callistachang/multi-worker ./worker
    

# push them to dockerhub!